In [20]:
import numpy as np
import pandas as pd

In [22]:
from sklearn.datasets import fetch_openml

housing = fetch_openml(data_id=42165, as_frame=True)

In [23]:
data=pd.DataFrame(housing.data)

In [24]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [53]:
data.colums=housing.feature_names

In [55]:
data['PRICE']=housing.target

In [57]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,PRICE
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [59]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
PRICE              0
Length: 81, dtype: int64

In [61]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,PRICE
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  PRICE          1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [89]:
X=data.iloc[:,:-1]
y=data.PRICE

In [109]:
# Handle missing values
X = X.fillna(0)

In [111]:
# Convert categorical columns into dummy/encoded variables
X = pd.get_dummies(X, drop_first=True)

In [113]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [115]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [117]:
# Prediction on the test dataset 
y_pred = regressor.predict(X_test)

In [119]:
# Predicting RMSE the Test set results 
from sklearn.metrics import mean_squared_error 
rmse = (np.sqrt(mean_squared_error(y_test, y_pred))) 
print(rmse)

49321.41143661217

In [121]:
# Scaling the dataset 
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

In [135]:
# Creating the neural network model 
import keras 
from keras.layers import Dense, Activation,Dropout 
from keras.models import Sequential 
 
model = Sequential() 
 
model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')

C:\Users\Sumit\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [137]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38883901440.0000
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38876643328.0000
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38854778880.0000
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38803075072.0000
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 38700777472.0000
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38528270336.0000
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38268448768.0000
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37904130048.0000
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37419819008.0000
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 36806713344.0000
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36047384576.0000
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 35147464704.0000
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 34096031744.0000
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 32917544960.0000
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31593617408.0000
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30154844160.0000
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28593911808.0000
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26932385792.0000
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25211039744.0000
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 23430504448.0000
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21626095616.0000
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19847413760.0000
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18121314304.0000
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16418497536.0000
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14785264640.0000
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13266977792.0000
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11867128832.0000
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10591975424.0000
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9481025536.0000
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8503354368.0000
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7664069120.0000
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6948845056.0000
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6344383488.0000
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5828545024.0000
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5399644672.0000
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5035308032.0000
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4727416320.0000
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4457574912.0000
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4226115328.0000
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4020225536.0000
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3841997824.0000
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3679245568.0000
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3536214272.0000
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3403624448.0000
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3287708928.0000
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3179508224.0000
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3083791616.0000
Epoch 48/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2994132480.0000
Epoch 49/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2914142464.0000
Epoch 50/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2840163584.0000
Epoch 51/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2772383232.0000
Epoch 52/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2709440768.0000
Epoch 53/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2651580160.0000
Epoch 54/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2597626112.0000
Epoch 55/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2547492096.0000
Epoch 56/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2499006976.0000
Epoch 57/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2457568512.0000
Epoch 58/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2413301504.0000
Epoch 59/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2372844032.0000
Epoch 60/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2335297792.0000
Epoch 61/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2299025920.0000
Epoch 62/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2264450560.0000
Epoch 63/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2230356480.0000
Epoch 64/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2198974208.0000
Epoch 65/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2167540736.0000
Epoch 66/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2136985600.0000
Epoch 67/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2110483840.0000
Epoch 68/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2078808192.0000
Epoch 69/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2051428736.0000
Epoch 70/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2025397760.0000
Epoch 71/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1998790272.0000
Epoch 72/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1973712512.0000
Epoch 73/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1948480896.0000
Epoch 74/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1924568320.0000
Epoch 75/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1900618752.0000
Epoch 76/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1877378816.0000
Epoch 77/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1855667328.0000
Epoch 78/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1834239744.0000
Epoch 79/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1813020416.0000
Epoch 80/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1791387520.0000
Epoch 81/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1771379456.0000
Epoch 82/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1751385728.0000
Epoch 83/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1730185728.0000
Epoch 84/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1712283904.0000
Epoch 85/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1693108096.0000
Epoch 86/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1674413568.0000
Epoch 87/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1656711552.0000
Epoch 88/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1638500608.0000
Epoch 89/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1619261952.0000
Epoch 90/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1601912704.0000
Epoch 91/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1586892544.0000
Epoch 92/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1568673536.0000
Epoch 93/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1552759552.0000
Epoch 94/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1537291264.0000
Epoch 95/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1521252608.0000
Epoch 96/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1504422400.0000
Epoch 97/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1489643776.0000
Epoch 98/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1475198720.0000
Epoch 99/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1460526720.0000
Epoch 100/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1447400064.0000

In [139]:
y_pred = model.predict(X_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

In [141]:
# Predicting RMSE the Test set results 
from sklearn.metrics import mean_squared_error 
rmse = (np.sqrt(mean_squared_error(y_test, y_pred))) 
print(rmse)

43565.987467289204